---
title: "HLM & What not..."
author: "Min Hwangbo"
date: "9/28/2020"
output:
  html_document:
    preserve_yaml: true
    toc: true
    toc_float: true
    keep_md: true
published: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Before we begin

## Context

* Below codes and references were documented throughout my PhD work at College of Education | Univ. of Washington
* If you are a UW student/staff, I highly recommend taking classes from Liz Sanders. These include the following: 
  * Hierarchical Linear Modeling (HLM | EDPSY576)
  * Structural Equation Modeling (SEM | EDPSY575)
* I also recommend referencing the text from [Snijers, T. A. B., & Bosker, R. J. (2012). *Multilevel Analysis: An Introduction to Basic and Advanced Multilevel Modeling, second edition. London etc.: Sage Publishers.*](https://www.stats.ox.ac.uk/~snijders/mlbook.htm)

## Acknowledgement
>*“The University of Washington acknowledges that it sits on Indigenous Land, which touches the shared waters of all tribes and bands within the Duwamish, Suquamish, Tulalip, and Muckleshoot Tribes.”*
 

# Overview: HLM?
> "Hierarchical Linear Modeling (HLM) is a complex form of ordinary least squares (OLS) regression that is used to analyze variance in the outcome variables when the predictor variables are at varying hierarchical levels; for
example, students in a classroom share variance according to their common teacher and common classroom." ([Woltman et al., 2012, p.52](http://www.tqmp.org/RegularArticles/vol08-1/p052/p052.pdf))

And what do we mean by `variance`? Based on [Wikipedia!](https://en.wikipedia.org/wiki/Variance):

* "Variance is the expectation of the squared deviation of a random variable from its mean."
* "Informally, it measures how far a set of numbers is spread out from their average value." 
* "Variance is an important tool in the sciences, where statistical analysis of data is common."
* "The variance is the square of the standard deviation, the second central moment of a distribution, and the covariance of the random variable with itself."

In sum, anyon who's interested in a statistical research modeling can apply HLM to explore shared variance in hierarchically structured data that has either 2-level or 3-level structure.

# ICC
Intraclass Correlation Coefficient (ICC) can be useful especially for a linear model that has a fixed variable as well as a random effect: the classic random intercept model. 

# 2-level model

# 3-level model

# Growth model

# Misc.
