---
title: "CyberSecurityToolkit_EdX_010721-"
author: "Min Hwangbo"
date: "1/7/2020"
output:
  html_document:
    preserve_yaml: true
    toc: true
    toc_float: true
    keep_md: true
published: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro

Instructor: [David Aucsmith](https://www.linkedin.com/in/aucsmith/)

> "The use of computers has grown exponentially... the ability to manage from and secured them and the skills required has not grown at nearly that rate."

# Summary

* Overview of history of internet
* Basic knowledge
* Risk, data analytics, threat intelligence, and the hunt

# Module 1: Evolution of Cybersecurity

## Inherent Internet Principles

* Best effort
* Difficult to track all the data/codes/nodes/messages
* Ambiguous delivery
* No centralized authentication
* Growth/increased inter-connectivity

## Codifying Internet Security

* Evolution: ARPANET (non-commercial only i.e. can't order a whole pizza) -> DNS (i.e. www.google.com) -> Add on features like Border Gateway Protocol (BGP)
* [Orange book | DoD Trusted Computer System Evaluation Criteria (TCSEC, 1985)](https://www.cs.clemson.edu/course/cpsc420/material/Evaluation/TCSEC.pdf): Great concept yet useless due to its lack of practicality
* Two major issues also include: 1) Issue of anonymity and 2) issue of duplicity

> "What is it that I do not know" when a system as designed meets the criteria or not or exceeds the specifications crietria? "How do you know whjen you're done looking?" [for those issues]

## Assumption of Breach

* Shift in our assumptions that the system is broken or will be breached as well as "How do we operate a system given the particular assumption?"
* Again, two things to consider:

### Adversaries

* Systems don't break, they are attacked.
* Even if you write a perfect code, doesn't mean it's going to survive.
* Can you build an indestructible airplane? Think of it as a similar concept

### Complexity

* We're building a complex system that's considered unknown architecture
* Can you project/predict what is going to happen at a battle? You'd consider sending a scout, build a perimeter, build a fence, start communicating, etc. 
* It just can't stand static. 

## Module 1 Resource: Criteria to Evaluate Computer and Network Security

> From *Computers at Risk: Computing in the Information Age (1991)*

